//#include <c/project/gen/stdio.h>
#include <c/project/gen/hpcontrol.h>
#include <c/project/gen/menucontrol.h>
#include <c/project/gen/timerevent.h>
#include <c/project/gen/button.h>
#include <c/project/gen/readbmp.h>
#include <c/project/gen/copy.h>
#include <c/project/gen/R.h>
#include <c/project/src/event.h>
#include <c/project/src/pause.h>
#include <c/project/src/main.h>