
//begin the strings
#define STR_OK 0
#define STR_CANCEL 1
#define STR_YES 2
#define STR_NO 3
#define STR_MENU 4
#define STR_SELECT 5
#define STR_BACK 6
#define STR_EXIT 7
#define STR_MSG 8
#define STR_ABOUT 9
#define STR_HELP 10
#define STR_FILE 11
#define STR_OPEN 12
#define STR_SAVE 13
#define STR_SAVETO 14
#define STR_INPUTNAME 15
#define STR_SAVESUC 16
#define STR_SAVEFAI 17
#define STR_INPUT 18
#define STR_OPENFILE 19
#define STR_OPENDIR 20
#define STR_NEWDIR 21
#define STR_CUT 22
#define STR_COPYFILE 23
#define STR_PASTE 24
#define STR_REMOVE 25
#define STR_RETURN 26
#define STR_REALREMOVE 27
#define STR_STARTREMOVE 28
#define STR_STARTFIND 29
#define STR_WARNING1 30
#define STR_RENAME 31
#define STR_HINT1 32
#define STR_TITLE 33
#define STR_EDITJMP1 34
#define STR_LOADERROR 35
#define STR_OTHER 36
#define STR_EDIT 37
#define STR_EDITCODE 38
#define STR_EDITUP 39
#define STR_EDITDOWN 40
#define STR_EDITPAT 41
#define STR_EDITJMP 42
#define STR_EDITCOPY 43
#define STR_EDITAFFIX 44
#define STR_EDITFADD 45
#define STR_EDITBADD 46
#define STR_EDITREMOVE 47
#define STR_1 48
#define STR_CANNOTPAT 49
#define STR_PAGEMAXNUM 50
#define STR_SMALLFONT 51
#define STR_HELPCONTENT 52
#define STR_NEW 53
#define STR_SETSUC 54
#define STR_RUN 55
#define STR_BUILDER 56
#define STR_BUILDERERROR 57
#define STR_TMPNAME 58

#define RES_STRING_COUNT 59
