[information]
projectname = res_str.mpr
filename = res_str.mrp
appname = res_str
appid = 1
version = 1
Visible = 1
cpu = 3
vendor = sky
Description = resource
config = res
[config_res]
output=..\res_str.mrp
[files] 
file0=res_lang0.rc

