[information]
projectname=Helloworld.mpr
filename=Helloworld.mrp
appname=Helloworld
appid=30254
version=101
visible=1
cpu=3
vendor=SkyMobi
output=Helloworld.mrp
description=This is HelloWorld!
include=../skysdk/include
config=mtk240


[config_mtk240]
output=240.mrp
bmp_mode=normal

[files]
file36 = web.c




